# Generated by Django 5.0.6 on 2024-07-08 22:00

import django.core.validators
import django.db.models.deletion
import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("username", models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        upload_to=main.utils.generate_random_photo,
                        verbose_name="preview",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to=main.utils.generate_random_filename,
                        verbose_name="video",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(40),
                        ],
                        verbose_name="title",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.customuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Video",
            },
        ),
        migrations.DeleteModel(
            name="Articles",
        ),
    ]
